added Delphi variant
emilybache/Theatrical-Players-Refactoring-Kata pull request #37
Opened 2024-03-20 12:41 UTC by ansgargosling

Hi there,

I added a Version with delphi-sourcecode,

2024-03-20 15:05 UTC, ansgargosling commented
Added Testcases
Fixed Currency-Output

2024-03-21 10:28 UTC, codecop commented
Thank you. Nice to see some Pascal. The code looks good. I added some review comments to the code, please address them.

2024-03-21 14:42 UTC, ansgargosling commented
> Thank you. Nice to see some Pascal. The code looks good. I added some review comments to the code, please address them.

Hi codecop,

thanks for your feedback. Maybe a dumb question, but where can i find your comments? This is my first contribution to an existing project, I would appreciate your help

2024-03-21 15:26 UTC, codecop requested changes
I do not know how to use GitHub review feature...

2024-03-21 15:27 UTC, codecop commented
Sorry I had not submitted the "review" but I was seeing it so I thought you would be seeing it too. Now it is here

2024-03-22 06:46 UTC, ansgargosling commented on delphi/main/TheatricalPlayers.dproj
Yes, this is a clean new project. I know, the dproj-files are a bit messy.

2024-03-22 06:47 UTC, ansgargosling commented on delphi/main/clrLoadData.pas
> +
Done!

2024-03-22 06:48 UTC, ansgargosling commented on delphi/main/clrStatementPrinter.pas
> +
Done

2024-03-22 06:48 UTC, ansgargosling commented on delphi/test/Win32/Debug/dunitx-results.xml
Added to ignore-list

2024-03-22 07:06 UTC, ansgargosling commented on delphi/test/uTestStatementPrinter.pas
Done!

2024-03-22 07:09 UTC, ansgargosling commented on delphi/test/uTestStatementPrinter.pas
> +  You earned 47 credits
Hmm? Didn't see this acually in my code. Try to push it again

2024-03-22 07:25 UTC, ansgargosling commented
no problem, you're a human, not a robot ;)
the changes are commited

2024-03-22 08:13 UTC, codecop commented
This looks good. Vote to merge @emilybache

2024-03-22 10:34 UTC, merged

2024-03-22 10:34 UTC, emilybache commented
Thankyou both for all your hard work.